---
version: 3
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
  ansible_core:
     package_pip: ansible-core
  ansible_runner:
     package_pip: ansible-runner
additional_build_files:
  - src: HORCM.tgz 
    dest: configs
  - src: horcm100.conf.j2
    dest: configs
  - src: hsds_cli-1.19.0.40.1008-py3-none-any.whl
    dest: configs
  - src: hitachivantara-vspone_block-4.8.2.tar.gz
    dest: configs
additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y install python3-pip
    - RUN $PKGMGR -y install tar
    - RUN $PKGMGR -y install gzip
    - COPY _build/configs/HORCM.tgz /tmp
    - RUN  tar xvzf /tmp/HORCM.tgz -C /
    - RUN /HORCM/horcminstall.sh
    - COPY _build/configs/horcm100.conf.j2 /tmp
    - COPY _build/configs/horcm101.conf.j2 /tmp
    - COPY _build/configs/hsds_cli-1.19.0.40.1008-py3-none-any.whl /tmp
    - RUN pip3 install /tmp/hsds_cli-1.19.0.40.1008-py3-none-any.whl
  append_final:
    - RUN chgrp 0 /etc && chmod g+w /etc
images:
  base_image:
    name: quay.io/centos/centos:stream9
options:
   package_manager_path: /usr/bin/dnf
